name: Mirror to GitLab
on: 
  push:
  delete:
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    environment: Mirror
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Push to GitLab Mirror
        run: |
          git remote add gitlab https://lmalheir:${{ secrets.GITLAB_TOKEN }}@gitlab.com/lmalheir/download-vsix-userscript.git
          git push --mirror gitlab
